version: '3'
services:
  server:
    build: ./server
    #container_name: server
    ports:
      - 5001:5001
    deploy:
      replicas: 2
  client:
    build: ./client
    #container_name: client
    ports:
      - 3000:3000
    deploy:
      replicas: 1
    depends_on:
      - server
