version: '3'
services:
  server:
    build: ./server
    #container_name: server
    image: 030411/server
    ports:
      - 5001:5001
    deploy:
      replicas: 3
  client:
    build: ./client
    #container_name: client
    image: 030411/client
    ports:
      - 3000:3000
    deploy:
      replicas: 3
    depends_on:
      - server
